import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home () {
    return (
    <div className={styles.container}>
        <Head>
        <title>Gift Basket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>My <a>Food Plan</a></h1>
                <p>Food is the supplement to your body and your beautiful mind. Don't be hesistate to take food. Healthy food always gives you the strength you need. So fullfilling your calorie nutrition with according to your body weight and hight we are here to support you. The snack basket will be prepared according to your calorie need.</p>
                <p>Price range is between 1000-3000 BDT</p>
                <br></br>
                <form>
                <h2>What food you need ? Vegitable or Nonvegitable ?</h2>
                <input type="text" id="Food"placeholder="type food you need"></input>
                <h2>Tell us something about your calorie need ? Between 200 calorie to 3500 calorie?</h2>
                <input id="calorie" placeholder="ex: 1200 calorie"></input>
                {/* <h2>Also tell us your snack basket budget,</h2>
                <input id="budget" placeholder="budget"></input> */}
                <h2>Delivery will conduct within 7 hours, is it okay ? Then tell your pick up time, </h2>
                <input id="delivery time" placeholder="dd/mm/yy"></input>
                <h2>Where you can collect your snack Basket ?</h2>
                <input type="text" id="location" placeholder="location"></input>
                <h2>Leave your mobile number here and please tell us your good name,</h2>
                <input id="nameNumber" placeholder="name: +8801*********"></input>
                <h2>Anything more you need ? Tell us here.. . .</h2>
                <textarea rows="4" cols="40"></textarea>
                <br></br>
                <a href=''><button className={styles.card} type="submit">Confirm Your Snack Basket Order</button></a>
                </form>
                <h4>For the Sylhet City Peoples pickup location is fixed at Lamabazar point near PanshiBazar opposite of UCBL Bank.</h4>
                
            </main>
            <a href='/' className={styles.back}> Back </a>

        <footer className={styles.footer}>
        <a
        //   href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        //   target="_blank"
        //   rel="noopener noreferrer"
        >
            <h5>If you chase to cancle the order please imediatelly call us at this +8801674859280 or +8801773496858 and tell your ordering name</h5>
            {/* <br></br>
            <p className={styles.footermain}>Powered by Orthodox</p> */}
          {/* Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
        </footer>
        {/* <script src="https://smtpjs.com/v3/smtp.js"></script>
        <script>
            function sendEmail(){
                Email.send({
                    Host : "smtp.gmail.com",
                    Username : "debkallol71@gmail.com",
                    Password : "password",
                    To : 'kamanashishdeb17@gmail.com',
                    From : "you@isp.com",
                    Subject : "This is the subject",
                    Body : "And this is the body"
                }).then(
                  message => alert(message)
                )
            }
        </script> */}
    </div>
        
    )
}